CREATE TABLE products(
  id VARCHAR(36),
  name VARCHAR(100),
  price DECIMAL(13,2),
  photo_url VARCHAR(255),
  user_id VARCHAR(36),
  created_date TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_date TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(id)
);

ALTER TABLE products ADD FOREIGN KEY(user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE ;